---

repos:
  # - repo: https://github.com/adrienverge/yamllint.git
  #   rev: v1.35.1  # Update me!
  #   hooks:
  #     - id: yamllint
  #       args: [-c, "./config.yamllint.yaml"]

  - repo: local
    hooks:
      - id: gitleaks-docker
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        language: docker_image
        entry: >
          -u root:root
          zricethezav/gitleaks:latest
          protect
          --verbose
          --redact
          --staged
        verbose: true

  # - repo: local
  #   hooks:
  #     - id: kics-scan
  #       name: Kics scan
  #       language: docker_image
  #       entry: >
  #         -v /etc/ssl/certs/ZscalerRootCertificate-2048-SHA256.pem:/etc/ssl/certs/cacert.pem
  #         -v ./kics.config.yaml:/kics/kics
  #         checkmarx/kics:latest scan -p /src
  #       verbose: true
