---
traefik:
  user: "traefik-user"
  home_dir: "/home/traefik-user/traefik"
  docker:
    network: "proxy"
  files:
    acme: "/home/traefik-user/traefik/data/acme.json"
    secrets: "/home/traefik-user/traefik/data/secrets.yml"
  permissions:
    config: "0755"
    acme: "0600"
    secrets: "0755"
