# playbooks/configure_builder_server.yml
- name: Configure Builder Server
  hosts: builders
  become: yes
  vars_files:
    - ../vars/configure_builder_server.yml
  roles:
    - git
    - clone_repositories