---
# playbooks/deploy_traefik.yml

- name: Deploy Traefik
  hosts: traefik
  become: true
  
  pre_tasks:
    - name: Include traefik secrets
      include_vars:
        file: "{{ paths.credentials }}/{{ repositories.credentials.paths.traefik.secrets }}"
        name: traefik_secrets

  tasks:
    - name: Copy Traefik files to target server
      ansible.builtin.copy:
        src: "{{ paths.homelab }}/apps/traefik/"
        dest: "{{ traefik.home }}/"
        owner: "{{ traefik.user }}"
        group: "{{ traefik.user }}"
        mode: "{{ traefik.permissions.config }}"

    - name: Copy Traefik secrets.yml
      ansible.builtin.copy:
        src: "{{ paths.credentials }}/{{ repositories.credentials.paths.traefik.secrets }}"
        dest: "{{ traefik.files.secrets }}"
        owner: "{{ traefik.user }}"
        group: "{{ traefik.user }}"
        mode: "{{ traefik.permissions.secrets }}"

    - name: Copy acme.json
      ansible.builtin.copy:
        src: "{{ paths.credentials }}/{{ repositories.credentials.paths.traefik.acme }}"
        dest: "{{ traefik.files.acme }}"
        owner: "{{ traefik.user }}"
        group: "{{ traefik.user }}"
        mode: "{{ traefik.permissions.acme }}"

    - name: Run secrets.sh script
      ansible.builtin.command: "./secrets.sh"
      args:
        chdir: "{{ traefik.home }}"
      become: true
      become_user: root

    - name: Create docker network proxy
      ansible.builtin.command: docker network create {{ traefik.docker.network }}
      ignore_errors: true
      register: docker_network_error

    - name: Display error message if network creation failed
      ansible.builtin.debug:
        msg: "Network creation failed: {{ docker_network_error.stderr }}"
      when: docker_network_error.failed

    - name: Run docker-compose
      ansible.builtin.command: docker-compose up -d --force-recreate
      args:
        chdir: "{{ traefik.home }}"
      become: true
      become_user: root
