---
# playbooks/deploy_traefik.yml

- name: Deploy Traefik
  hosts: traefik
  become: true

  pre_tasks:
    - name: Include traefik secrets
      include_vars:
        file: "{{ paths.credentials }}/{{ repositories.credentials.paths.ansible_vars }}/traefik/secrets.yml"
        name: traefik_secrets

  tasks:
    - name: Create Traefik directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ traefik_secrets.traefik_system.user }}"
        group: "{{ traefik_secrets.traefik_system.user }}"
        mode: "{{ traefik.permissions.config }}"
      loop:
        - "{{ traefik_secrets.traefik_system.home_dir }}"
        - "{{ traefik_secrets.traefik_system.home_dir }}/data"

    - name: Copy Traefik configuration files
      ansible.builtin.copy:
        src: "{{ paths.homelab }}/apps/traefik/{{ item }}"
        dest: "{{ traefik_secrets.traefik_system.home_dir }}/{{ item }}"
        owner: "{{ traefik_secrets.traefik_system.user }}"
        group: "{{ traefik_secrets.traefik_system.user }}"
        mode: "{{ traefik.permissions.config }}"
      loop:
        - docker-compose.yml
        - data/config.yml
        - data/traefik.yml
        - secrets.sh

    - name: Copy Traefik secrets.yml
      ansible.builtin.copy:
        src: "{{ paths.credentials }}/{{ repositories.credentials.paths.traefik.secrets }}"
        dest: "{{ traefik_secrets.traefik_system.files.secrets }}"
        owner: "{{ traefik_secrets.traefik_system.user }}"
        group: "{{ traefik_secrets.traefik_system.user }}"
        mode: "{{ traefik.permissions.secrets }}"

    - name: Copy acme.json
      ansible.builtin.copy:
        src: "{{ paths.credentials }}/{{ repositories.credentials.paths.traefik.acme }}"
        dest: "{{ traefik_secrets.traefik_system.files.acme }}"
        owner: "{{ traefik_secrets.traefik_system.user }}"
        group: "{{ traefik_secrets.traefik_system.user }}"
        mode: "{{ traefik.permissions.acme }}"

    - name: Run secrets.sh script
      ansible.builtin.command: "./secrets.sh"
      args:
        chdir: "{{ traefik_secrets.traefik_system.home_dir }}"
      become: true
      become_user: root

    - name: Create docker network proxy
      ansible.builtin.command: docker network create {{ traefik.docker.network }}
      ignore_errors: true
      register: docker_network_error

    - name: Display error message if network creation failed
      ansible.builtin.debug:
        msg: "Network creation failed: {{ docker_network_error.stderr }}"
      when: docker_network_error.failed

    - name: Run docker-compose
      ansible.builtin.command: docker-compose up -d --force-recreate
      args:
        chdir: "{{ traefik_secrets.traefik_system.home_dir }}"
      become: true
      become_user: root
