---
- name: Destroy K3s VMs
  hosts: builders
  become: true
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Create each master
      with_items: "{{ groups['master'] }}"
      tasks:
        - name: Get target IP from inventory
          set_fact:
            target_ip: "{{ hostvars[item].ansible_host }}"

        - name: Ping the target IP
          shell: ping -c 1 -W {{ target_ip }}
          register: ping_result
          ignore_errors: true

        - name: Destroy vm if target is alive
          command: "terraform destroy -auto-approve {{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}/{{ item }}.tfvars"
          args:
            chdir: "{{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}/"
          when: ping_result.rc == 0

    - name: Create each node
      with_items: "{{ groups['node'] }}"
      tasks:
        - name: Get target IP from inventory
          set_fact:
            target_ip: "{{ hostvars[item].ansible_host }}"

        - name: Ping the target IP
          shell: ping -c 1 -W {{ target_ip }}
          register: ping_result
          ignore_errors: true

        - name: Build vm if target is not alive
          command: "terraform destroy -auto-approve {{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}/{{ item }}.tfvars"
          args:
            chdir: "{{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}/"
          when: ping_result.rc == 0
