- name: Deploy K3s
  hosts: builders
  become: true
  
  pre_tasks:
    - name: Wait for all nodes to be ready
      ansible.builtin.wait_for:
        host: "{{ hostvars[item].ansible_host }}"
        port: 22
        timeout: 300
      loop: "{{ groups['master'] + groups['node'] }}"
      register: nodes_ready

    - name: Deploy K3s cluster
      ansible.builtin.command: "ansible-playbook site.yml -i inventory/my-cluster/hosts.ini"
      args:
        chdir: "{{ paths.k3s }}"
      when: nodes_ready is success
