---
- name: Get target IP from inventory
  set_fact:
    target_ip: "{{ hostvars[item].ansible_host }}"

- name: Ping the target IP
  shell: "ping -c 1 -W 1 {{ target_ip }}"
  register: ping_result
  ignore_errors: true

- name: Copy template files for VM if not alive
  synchronize:
    src: "{{ homelab_dir }}/templates/terraform-base-template/"
    dest: "{{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}"
    mode: push

# - name: Copy template files for VM if not alive
#   command: "cp -R {{ homelab_dir }}/templates/terraform-base-template {{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}"
#   when: ping_result.rc != 0

- name: Copy config file for VM if not alive
  command: "cp {{ credentials_dir }}/k3s/{{ item }}.tfvars {{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}/{{ item }}.tfvars"
  when: ping_result.rc != 0

- name: Initiate Terraform
  command: "terraform init"
  args:
    chdir: "{{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}/"
  when: ping_result.rc != 0

- name: Build VM if target is not alive
  command: "terraform apply -auto-approve {{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}/{{ item }}.tfvars"
  args:
    chdir: "{{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}/"
  when: ping_result.rc != 0
