---
- name: Destroy K3s VMs
  hosts: localhost
  gather_facts: false
  vars:
    target_vm: ""  # Can be set via --extra-vars "target_vm=k3s-master-1"

  tasks:
    - name: Set VM list
      set_fact:
        vm_list: "{{ [target_vm] if target_vm != '' else (groups['master'] + groups['node']) }}"

    - name: Destroy VMs
      ansible.builtin.command: >
        terraform destroy -auto-approve 
        -var-file='{{ paths.terraform }}/proxmox/terraform/k3s/{{ item }}/{{ item }}.tfvars'
      args:
        chdir: "{{ paths.terraform }}/proxmox/terraform/k3s/{{ item }}/"
      loop: "{{ vm_list }}"
      register: terraform_destroy

    - name: Wait for VMs to be destroyed
      ansible.builtin.wait_for:
        host: "{{ hostvars[item].ansible_host }}"
        port: 22
        timeout: 300
        state: stopped
      loop: "{{ vm_list }}"
      when: terraform_destroy is success
