---
- name: Destroy VM
  ansible.builtin.command: >
    terraform destroy -auto-approve 
    -var-file='{{ paths.terraform }}/proxmox/terraform/k3s/{{ item }}/{{ item }}.tfvars'
  args:
    chdir: "{{ paths.terraform }}/proxmox/terraform/k3s/{{ item }}/"
  ignore_errors: true
  register: terraform_destroy

- name: Wait for VM to be fully destroyed
  ansible.builtin.wait_for:
    host: "{{ hostvars[item].ansible_host }}"
    port: 22
    timeout: 300
    state: stopped
  when: "terraform_destroy.rc == 0"
