---
- name: Get target IP from inventory
  set_fact:
    target_ip: "{{ hostvars[item].ansible_host }}"

- name: Ping the target IP
  shell: "ping -c 1 -W 1 {{ target_ip }}"
  register: ping_result
  ignore_errors: true

- name: Build VM if target is alive
  command: "terraform destroy -var-file='{{ terraform_dir }}/proxmox/terraform/k3s/{{ item }}/{{ item }}.tfvars'"
  args:
    chdir: "{{ terraform_dir }}/proxmox/terraform/k3s/{{ item }}/"
  when: ping_result.rc == 0
