---
- name: Get target IP from inventory
  set_fact:
    target_ip: "{{ hostvars[item].ansible_host }}"

- name: Ping the target IP
  shell: "ping -c 1 -W 1 {{ target_ip }}"
  register: ping_result
  ignore_errors: true

- name: Copy config file for VM if not alive
  copy:
    src: "{{ homelab_dir }}/templates/terraform-base-template"
    dest: "{{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}"
    owner: ansible
    group: ansible
    mode: '0755'
    recurse: yes
  when: ping_result.rc != 0

- name: Copy config file for VM if not alive
  copy:
    src: "{{ credentials_dir }}/k3s/{{ item }}.tfvars"
    dest: "{{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}/{{ item }}.tfvars"
    owner: ansible
    group: ansible
    mode: '0644'
    recurse: yes
  when: ping_result.rc != 0

- name: Build VM if target is not alive
  command: "terraform apply -auto-approve {{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}/{{ item }}.tfvars"
  args:
    chdir: "{{ homelab_dir }}/proxmox/terraform/k3s/{{ item }}/"
  when: ping_result.rc != 0
