---
- name: Create K3s VMs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create terraform directories and copy templates
      block:
        - name: Create terraform directories
          ansible.builtin.file:
            path: "{{ paths.terraform }}/proxmox/terraform/k3s/{{ item }}"
            state: directory
            mode: '0755'
          loop: "{{ groups['master'] + groups['node'] }}"

        - name: Copy terraform templates
          ansible.builtin.synchronize:
            src: "{{ paths.homelab }}/templates/terraform-base-template/"
            dest: "{{ paths.terraform }}/proxmox/terraform/k3s/{{ item }}"
            mode: push
          loop: "{{ groups['master'] + groups['node'] }}"

        - name: Copy tfvars files
          ansible.builtin.copy:
            src: "{{ paths.credentials }}/k3s/{{ item }}.tfvars"
            dest: "{{ paths.terraform }}/proxmox/terraform/k3s/{{ item }}/{{ item }}.tfvars"
            mode: '0644'
          loop: "{{ groups['master'] + groups['node'] }}"

    - name: Initialize and apply terraform
      block:
        - name: Initialize terraform
          ansible.builtin.command: terraform init
          args:
            chdir: "{{ paths.terraform }}/proxmox/terraform/k3s/{{ item }}/"
          loop: "{{ groups['master'] + groups['node'] }}"

        - name: Create VMs
          ansible.builtin.command: >
            terraform apply -auto-approve 
            -var-file='{{ paths.terraform }}/proxmox/terraform/k3s/{{ item }}/{{ item }}.tfvars'
          args:
            chdir: "{{ paths.terraform }}/proxmox/terraform/k3s/{{ item }}/"
          loop: "{{ groups['master'] + groups['node'] }}"
