- name: Destroy K3s
  hosts: builders
  become: true

  tasks:
    - name: Reset K3s cluster
      ansible.builtin.command: "ansible-playbook reset.yml -i inventory/my-cluster/hosts.ini"
      args:
        chdir: "{{ paths.k3s }}"
