---
# playbooks/update_repositories.yml

- name: Configure Builder Server
  hosts: builders
  become: true
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present

    - name: Pull latest changes for homelab repository
      git:
        repo: "{{ homelab_repo_url }}"
        dest: /home/ansible/homelab
        version: develop
        key_file: /home/ansible/.ssh/github_rsa
        accept_hostkey: true
        update: true

    - name: Pull latest changes for credentials repository
      git:
        repo: "{{ credentials_repo_url }}"
        dest: /home/ansible/credentials
        version: develop
        key_file: /home/ansible/.ssh/github_rsa
        accept_hostkey: true
        update: true
