# roles/git/tasks/main.yml
- name: Check if GitHub SSH key exists
  stat:
    path: /home/ansible/.ssh/github_rsa
  register: github_key_stat

- name: Copy GitHub private key
  copy:
    src: "{{ github_private_key_src }}"
    dest: /home/ansible/.ssh/github_rsa
    owner: ansible
    group: ansible
    mode: '0600'
  when: not github_key_stat.stat.exists

- name: Start SSH agent
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add /home/ansible/.ssh/github_rsa
  become: yes
  become_user: ansible
  when: not github_key_stat.stat.exists