# roles/update_repositories/tasks/main.yml
- name: Ensure git is installed
  apt:
    name: git
    state: present

- name: Pull latest changes for homelab repository
  git:
    repo: "{{ homelab_repo_url }}"
    dest: /home/ansible/homelab
    version: develop
    key_file: /home/ansible/.ssh/github_rsa
    accept_hostkey: yes
    update: yes

- name: Pull latest changes for credentials repository
  git:
    repo: "{{ credentials_repo_url }}"
    dest: /home/ansible/credentials
    version: develop
    key_file: /home/ansible/.ssh/github_rsa
    accept_hostkey: yes
    update: yes
