apiVersion: v1
kind: Secret
metadata:
  name: infisical-pg-admin-credentials-secret
  namespace: infisical
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: ""
  password: ""
