# roles/clone_repositories/tasks/main.yml
- name: Ensure git is installed
  apt:
    name: git
    state: present

- name: Cloning homelab repository
  git:
    repo: "{{ homelab_repo_url }}"
    dest: /home/ansible/homelab
    version: develop
    key_file: /home/ansible/.ssh/github_rsa
    accept_hostkey: yes
    update: yes

- name: Cloning credentials repository
  git:
    repo: "{{ credentials_repo_url }}"
    dest: /home/ansible/credentials
    version: develop
    key_file: /home/ansible/.ssh/github_rsa
    accept_hostkey: yes
    update: yes

- name: Set ownership of credentials directory
  file:
    path: /home/ansible/homelab
    state: directory
    owner: ansible
    group: ansible
    recurse: yes

- name: Set ownership of credentials directory
  file:
    path: /home/ansible/credentials
    state: directory
    owner: ansible
    group: ansible
    recurse: yes