env = "dev"
proxmox_api_url = ""  # Your Proxmox IP Address
proxmox_api_token_id = ""  # API Token ID
proxmox_api_token_secret = ""
proxmox_iso_file = "local:iso/ubuntu-20.04.6-live-server-amd64.iso"
proxmox_node = ""
vm_name = "base-template"
agent = "1"
cores = "1"
memory = "2048"
http_bind_address = ""
http_bind_port = ""
ssh_username = "cloudinit-admin"
ssh_private_key_file = "./files/ssh/cloudinit_rsa"